### ISSUE TITLE
What can I do to help?

### ISSUE THREAD

**Issue by cena** [beerjs/msp#2]
Hey y'all!  I randomly stumbled across the beer.js group and found the MSP chapter.  I'm a advanced beginner-ish JSer and homebrewer.  What can I do to help make this happen? :)

**Comment by markscripter** [comment]
Welcome! Thanks for taking the interest in contributing! Like you, we also just found beerjs recently and are in the process of trying to get this setup in MSP.

We are currently in the process of getting some items setup. Depending on how things go, we are looking to schedule our first gathering for sometime in January or early February. 

If you haven't seen, we have a slack group you can join, tcinteractive.slack.com, by asking @thejohnsmith for an invite. We will be using slack as an informal conversation tool for planning and discussing ideas with each other, while github will be used for information about gatherings and informing watchers of what's going on.

Again, welcome and thanks for wanting to contribute!

**Comment by markscripter** [comment]
Closing as @cena has joined the group.
