### ISSUE TITLE
1st Meeting 4/6

### ISSUE THREAD

**Issue by markscripter** [beerjs/msp#4]
So it's about time we start meeting. For the first meeting, I'd like to get together and discuss what our goals are with BeerJS and get input from others. 

Location: Lakes & Legends
Website: http://lakesandlegends.com/
https://goo.gl/maps/fWUtLM1Sefw
Date: 6th April 2016
Time: 6PM

**Comment by thejohnsmith** [comment]
I'll be attending.

**Comment by MathiasaurusRex** [comment]
I'll be out of town -- have fun!

**Comment by markscripter** [comment]
Updating the date due to conflicts.
